server.port=443

server.http2.enabled=true

spring.thymeleaf.cache=true
logging.level.org.springframework.data.convert.CustomConversions: ERROR

spring.mongodb.host=10.0.20.14
spring.mongodb.port=27017
spring.mongodb.database=video-2022
spring.mongodb.authentication-database=admin
spring.mongodb.username=${MONGODB_USERNAME:video-2022}
spring.mongodb.password=${MONGODB_PASSWORD}
spring.data.mongodb.auto-index-creation=true

server.ssl.key-store=classpath:Tomcat8_4_oneclick.video.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD}

internal-base-url=https://oneclick.video
external-base-url=${internal-base-url}
short-url-service=http://10.0.16.16:5027/add
youtube-service-url=https://video-youtube-video-hongkong-iabsngmqbv.cn-hongkong.fcapp.run

aliyun.oss.video.bucket=video-2022-prod
aliyun.oss.video.endpoint=oss-cn-beijing.aliyuncs.com
aliyun.oss.video.internal-endpoint=oss-cn-beijing-internal.aliyuncs.com
aliyun.oss.video.accessKeyId=${ALIYUN_OSS_VIDEO_ACCESS_KEY_ID:}
aliyun.oss.video.secretKey=${ALIYUN_OSS_VIDEO_SECRET_KEY:}
aliyun.oss.video.accessBaseUrl=https://video-2022-prod.oss-cn-beijing.aliyuncs.com/

aliyun.oss.data.bucket=oss-data-bucket
aliyun.oss.data.endpoint=oss-cn-beijing.aliyuncs.com
aliyun.oss.data.internal-endpoint=oss-cn-beijing-internal.aliyuncs.com
aliyun.oss.data.accessKeyId=${ALIYUN_OSS_DATA_ACCESS_KEY_ID:}
aliyun.oss.data.secretKey=${ALIYUN_OSS_DATA_SECRET_KEY:}
aliyun.oss.data.inventory-prefix=video-2022-prod/inventory/video-2022-prod/inventory-rule
aliyun.oss.data.accesslog-prefix=video-2022-prod/accesslog

aliyun.mps.accessKeyId=${ALIYUN_MPS_ACCESS_KEY_ID:}
aliyun.mps.secretKey=${ALIYUN_MPS_SECRET_KEY:}

aliyun.apigateway.ip.appcode=${ALIYUN_APIGATEWAY_IP_APPCODE:}

aliyun.cf.video-2022.get-oss-object-md5.url=https://get-ossbject-md-video-prod-uiswyunudj.cn-beijing.fcapp.run

callback.secret=${CALLBACK_SECRET:}


