FROM centos:7

# 更新系统包并安装所需软件包
RUN yum -y update && \
    yum install -y java-11-openjdk epel-release ffmpeg clang gcc make wget curl vim \
    openssl-devel bzip2-devel libffi-devel zlib-devel xz-devel && \
    yum clean all

# 下载安装 Python3
RUN yum -y remove python3 && \
    cd /usr/src && \
    wget https://www.python.org/ftp/python/3.10.13/Python-3.10.13.tgz && \
    tar xzf Python-3.10.13.tgz && \
    cd Python-3.10.13 && \
    ./configure --enable-optimizations && \
    make altinstall && \
    rm /usr/src/Python-3.10.13.tgz && \
    python3.10 -V && \
    ln -s /usr/local/bin/python3.10 /usr/bin/python3

# 升级 pip 到最新版本
RUN pip3.10 install -i https://mirrors.aliyun.com/pypi/simple/ --upgrade pip

# 安装 yt-dlp
RUN pip3.10 install -i https://mirrors.aliyun.com/pypi/simple/ yt-dlp
