FROM centos:7
RUN yum -y update
RUN yum install -y java-11-openjdk epel-release python3-pip ffmpeg clang gcc make wget \
    openssl-devel bzip2-devel libffi-devel zlib-devel xz-devel \

RUN cd /usr/src
RUN wget https://www.python.org/ftp/python/3.7.11/Python-3.7.11.tgz
RUN tar xzf Python-3.7.11.tgz
RUN cd Python-3.7.11
RUN ./configure --enable-optimizations
RUN make altinstall
RUN rm /usr/src/Python-3.7.11.tgz
RUN python3.7 -V

RUN pip3 install -i https://mirrors.aliyun.com/pypi/simple/ yt-dlp